name: Update gist with WakaTime stats
# on: [workflow_dispatch]
on:
  workflow_dispatch:
     input:
  schedule:
    - cron: "0 0 * * *"
#  schedule:
#    - cron: "0 0 * * *"
  
      
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: hansololai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: fe21c01e72b09e708f1007d3d3fdcca7
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
